services:
  mydealz-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mydealz-monitor
    environment:
      DEAL_URL: ${DEAL_URL}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      POLL_SECONDS: ${POLL_SECONDS:-60}
    volumes:
      - mydealz_state:/app/MyDealz-Deal
    restart: unless-stopped

volumes:
  mydealz_state:
